FROM r.cfcr.io/macioa/macioa/build_deps:master
#AUTOGEN AND CONFIGURE DAPS
RUN su && cd /DAPS/ && bash ./autogen.sh
RUN su && cd /DAPS/ && bash ./configure --with-libressl

#BUILD AND INSTALL DAPS
RUN su && cd /DAPS/ && make 
RUN su && cd /DAPS/ && make install 

CMD /bin/bash