FROM ubuntu:16.04

#INSTALL EXPLORER LIBS
RUN apt-get update
RUN apt-get install npm nano -y --fix-missing

#COPY SRC
RUN mkdir -p /DAPS/
COPY /assets/block-explorer/* /DAPS/

#INSTALL NODE_MODULES
RUN cd /DAPS/ && npm install

EXPOSE 3001

CMD /bin/bash -c "trap: TERM INT; sleep infinity & wait"